GET http://localhost:3001/api/posts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM

###
GET http://localhost:3001/api/posts/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM

###
GET http://localhost:3001/api/posts/wall/@johndoe
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM

###
DELETE http://localhost:3001/api/posts/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM

###
POST http://localhost:3001/api/posts/seed
