http://localhost:3001

###
GET http://localhost:3001/api/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM

###
GET http://localhost:3001/api/users/handle/@joannadoe
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM

###
GET http://localhost:3001/api/users/624f396095311be558d69ffc
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2FubmEiLCJsYXN0TmFtZSI6IkRvZSIsImhhbmRsZSI6IkBqb2FubmFkb2UiLCJlbWFpbCI6IkpvYW5uYUBlbWFpbC5jb20iLCJwaWMiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi8yLmpwZyIsImlkIjoyLCJpYXQiOjE2NDkwOTg1NDd9.ZvLgeTWWJNYsUK_tOXMge77JB8HT9LX6Ajk_43pCWaM
###
DELETE  http://localhost:3001/api/users/1

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "firstName": "Andres",
  "lastName": "Mena",
  "handle": "@andresmena",
  "password": "password",
  "email": "andres@email.com",
  "pic": "https://randomuser.me/api/portraits/men/4.jpg"
}

###
PATCH  http://localhost:3001/api/users/624f396095311be558d69ffd
Content-Type: application/json

{
  "password": "password"
}

###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "Joanna@email.com",
  "password": "passwordtest"
}

###
POST http://localhost:3001/api/users/seed
