http://localhost:3001

###
GET http://localhost:3001/api/users
Authorization: bearer {{ login.response.body.data.token }}

###
GET http://localhost:3001/api/users/handle/@joannadoe
Authorization: bearer {{ login.response.body.data.token }}

###
GET http://localhost:3001/api/users/624f396095311be558d69ffc
Authorization: bearer {{ login.response.body.data.token }}

###
DELETE  http://localhost:3001/api/users/1

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "firstName": "Andres",
  "lastName": "Mena",
  "handle": "@andresmena",
  "password": "password",
  "email": "andres@email.com",
  "pic": "https://randomuser.me/api/portraits/men/4.jpg"
}

###
PATCH  http://localhost:3001/api/users/624f396095311be558d69ffd
Content-Type: application/json

{
  "password": "password"
}


###
# @name login 
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "Joanna@email.com",
  "password": "password"
}

###
POST http://localhost:3001/api/users/seed

###
https://api.openweathermap.org/data/2.5/weather?q=New Paltz&appid={{$dotenv OPENWEATHER_KEY}}

###
https://api.coinbase.com/v2/exchange-rates

###
https://maps.googleapis.com/maps/api/place/textsearch/json?query=New+York&key={{$dotenv GOOGLE_API_KEY_1}}
